### PR TITLE
chore: upgrade webpack and related packages to recent versions

### PR DESCRIPTION
**Pull request by acozzette**
Upgraded packages to the most widely-used recent stable versions:

  webpack:              5.76.2  → 5.106.2  (latest 5.x)
  webpack-cli:          5.0.1   → 5.1.4    (latest 5.x)
  webpack-dev-server:   4.13.1  → 5.2.3    (latest; v5 requires webpack 5,
                                             so e2e/smoke/v4 stays on 4.15.2)
  html-webpack-plugin:  5.5.0   → 5.6.7
  sass-loader:          13.1.0  → 16.0.8
  sass:                 1.55.0  → 1.99.0
  css-loader:           6.7.3   → 7.1.4
  mini-css-extract-plugin: 2.7.5 → 2.10.2
  ts-loader:            9.4.2   → 9.5.7
  typescript:           4.8.4   → 5.9.3    (latest 5.x; held back from 6.0
                                             as it was just released)
  js-yaml:              4.1.0   → 4.1.1

The e2e/smoke golden files (expected-v4.js_, expected-v5.js_) and the webpack/tests golden files were regenerated, as webpack 5.106.2 emits slightly different output (arrow functions, different module ID hashes, removed a MODULE_NOT_FOUND guard block).

Fix ajv MODULE_NOT_FOUND in e2e/loaders
-----------------------------------------
e2e/loaders/MODULE.bazel uses `no_optional = True` in npm_translate_lock, which tells rules_js to skip packages listed as optionalDependencies in the lockfile snapshot. After upgrading mini-css-extract-plugin to 2.10.2 its dep chain became: schema-utils@4 → ajv-formats@2.1.1, where ajv is declared as an optional peer. pnpm records it under optionalDependencies in the snapshot, so rules_js excluded it from the Bazel sandbox entirely, causing a MODULE_NOT_FOUND at runtime.

Fix: add ajv as an explicit devDependency (8.20.0) so it gets a top-level node_modules/ajv symlink that Node.js module resolution can reach by traversing up from ajv-formats' virtual-store path. Also added :node_modules/ajv to the deps of the three webpack_bundle rules that use mini-css-extract-plugin (:css, :css_expected, :html).

---

### Test plan

- Covered by existing test cases

### CODE REVIEW

File: e2e/loaders/BUILD.bazel [hunk 1]
```diff
@@ -20,6 +20,7 @@ webpack_bundle(
     output_dir = True,
     webpack_config = ":webpack.css.cjs",
     deps = [
+        ":node_modules/ajv",
```
Comment (jbedard) [inline e2e/loaders/BUILD.bazel]: Do we directly import this? Why would this have to be added to the BUILD?

**Review by jbedard — APPROVED** [review]

File: e2e/loaders/BUILD.bazel (hunk 1 above)
Comment (acozzette) [reply e2e/loaders/BUILD.bazel]: We don't import it ourselves, but without these lines I get an error like this:
```
[webpack-cli] Error: Cannot find module 'ajv'
Require stack:
- /home/adam/.cache/bazel/_bazel_adam/85a581dce67e87b69c5c552ca31982b0/sandbox/processwrapper-sandbox/5/execroot/_main/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/ajv-formats@2.1.1_ajv@8.20.0/node_modules/ajv-formats/dist/limit.js
```

This seems to have something to do with the way ajv-formats takes a dependency on ajv:
```
  "dependencies": {
    "ajv": "^8.0.0"
  },
  "peerDependencies": {
    "ajv": "^8.0.0"
  },
  "peerDependenciesMeta": {
    "ajv": {
      "optional": true
    }
  },
```

Actually I wonder now if this is a bug in rules_js, because one would expect that even if the peer dependency is not provided, we should still fall back on a regular dependency.

Comment (acozzette) [reply e2e/loaders/BUILD.bazel]: The dep in the lockfile looks like this:
```  ajv-formats@2.1.1:
    resolution: {integrity: sha512-Wx0Kx52hxE7C18hkMEggYlEifqWZtYaRgouJor+WMdPnQyEK13vgEWyVNup7SoeeoLMsr4kf5h6dOW11I15MUA==}
    peerDependencies:
      ajv: ^8.0.0
    peerDependenciesMeta:
      ajv:
        optional: true
```

And it seems that the `no_optional = True` flag on `npm_translate_lock` is causing it to skip over this dependency altogether.

Comment (jbedard) [reply e2e/loaders/BUILD.bazel]: Seems like it isn't optional then? lol

You can decide how you want to fix it:
* what you have
* remove `no_optional = True`
* `pnpm.packageExtensions` (or whatever its called now) to declare it as a `dependency` instead of `peerDependency`

I doubt this e2e test has any reason to do `no_optional` so maybe that will be simplest?

Comment (acozzette) [reply e2e/loaders/BUILD.bazel]: OK, I just removed `no_optional` to unblock this. I do suspect that this is a bug in rules_js, though. My understanding is that this pattern of having a package appear as both a regular dependency and optional peer dependency is supposed to result in using the peer dependency if available and otherwise falling back on the regular dependency. But we seem to be finding that the peer dependency is available and then we're still not using it anyway.

Comment (jbedard) [reply e2e/loaders/BUILD.bazel]: Doesn't removing the `":node_modules/ajv"` imply it's working? 

Either way this PR LGTM atm

**Review by jbedard — APPROVED** [review]

File: e2e/loaders/BUILD.bazel (hunk 1 above)
Comment (acozzette) [reply e2e/loaders/BUILD.bazel]: I works now with `no_optional` removed, but the fact that this is necessary seems like a bug to me.

Comment (acozzette) [reply e2e/loaders/BUILD.bazel]: I'll go ahead and merge this and perhaps file an issue for that, though.
